---
- name: Ensure Mincraft group is present
  ansible.builtin.group:
    name: "{{ minecraft_group }}"
    gid: "{{ minecraft_gid }}"
    state: present

- name: Ensure Minecraft user is present
  ansible.builtin.user:
    create_home: false
    group: "{{ minecraft_group }}"
    name: "{{ minecraft_user }}"
    shell: /sbin/nologin
    system: true
    uid: "{{ minecraft_uid }}"

- name: Ensure Docker image is vanilla flavor
  ansible.builtin.set_fact:
    docker_image: "dcjulian29/minecraft:{{ minecraft_version }}"
  when:
    - not minecraft_paper

- name: Ensure Docker image is paper flavor
  ansible.builtin.set_fact:
    docker_image: "dcjulian29/minecraft:{{ minecraft_version }}-paper"
  when: minecraft_paper

- name: Pull Minecraft docker image
  community.docker.docker_image:
    force_source: true
    name: "{{ docker_image }}"
    source: pull
  notify: Remove minecraft

- name: Ensure all handlers run before continuing
  ansible.builtin.meta: flush_handlers

- name: Ensure Minecraft folder exists
  ansible.builtin.file:
    access_time: preserve
    group: "{{ minecraft_group }}"
    mode: "0750"
    modification_time: preserve
    owner: "{{ minecraft_user }}"
    path: "{{ minecraft_data }}"
    state: directory

- name: Ensure banned-ips.json is configured
  ansible.builtin.copy:
    content: "{{ minecraft_banned_ips | to_json }}"
    dest: "{{ minecraft_data }}/banned-ips.json"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
  notify: Restart minecraft

- name: Ensure banned-players.json is configured
  ansible.builtin.copy:
    content: "{{ minecraft_banned_players | to_json }}"
    dest: "{{ minecraft_data }}/banned-players.json"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
  notify: Restart minecraft

- name: Ensure ops.json is configured
  ansible.builtin.template:
    dest: "{{ minecraft_data }}/ops.json"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
    src: ops.json.j2
  notify: Restart minecraft

- name: Ensure server.properties is configured
  ansible.builtin.template:
    dest: "{{ minecraft_data }}/server.properties"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
    src: server.properties.j2
  notify: Restart minecraft

- name: Ensure whitelist.json is configured
  ansible.builtin.copy:
    content: "{{ minecraft_whitelist | to_json }}"
    dest: "{{ minecraft_data }}/whitelist.json"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
  notify: Restart minecraft

- name: Ensure bukkit.yml is configured if applicable
  ansible.builtin.template:
    dest: "{{ minecraft_data }}/bukkit.yml"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
    src: bukkit.yml.j2
  when: minecraft_paper
  notify: Restart minecraft

- name: Ensure spigot.yml is configured if applicable
  ansible.builtin.template:
    dest: "{{ minecraft_data }}/spigot.yml"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
    src: spigot.yml.j2
  when: minecraft_paper
  notify: Restart minecraft

- name: Ensure Minecraft Paper configuration folder exists
  ansible.builtin.file:
    access_time: preserve
    group: "{{ minecraft_group }}"
    mode: "0750"
    modification_time: preserve
    owner: "{{ minecraft_user }}"
    path: "{{ minecraft_data }}/config"
    state: directory
  when: minecraft_paper

- name: Ensure paper-global.yml is configured if applicable
  ansible.builtin.template:
    dest: "{{ minecraft_data }}/config/paper-global.yml"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
    src: paper-global.yml.j2
  when: minecraft_paper
  notify: Restart minecraft

- name: Ensure paper-world-defaults.yml is configured if applicable
  ansible.builtin.template:
    dest: "{{ minecraft_data }}/config/paper-world-defaults.yml"
    group: "{{ minecraft_group }}"
    mode: "0640"
    owner: "{{ minecraft_user }}"
    src: paper-world-defaults.yml.j2
  when: minecraft_paper
  notify: Restart minecraft

- name: Ensure plugin folder exists.
  ansible.builtin.file:
    access_time: preserve
    group: "{{ minecraft_group }}"
    mode: "0750"
    modification_time: preserve
    owner: "{{ minecraft_user }}"
    path: "{{ minecraft_data }}/plugins"
    state: directory
  when: minecraft_paper

- name: Ensure Plugins are installed.
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: '{{ minecraft_data }}/plugins/'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0640"
  with_items: "{{ minecraft_plugins }}"
  when: minecraft_paper

- name: Ensure Docker volumes to mount are vanilla flavor
  ansible.builtin.set_fact:
    docker_volumes: "{{ vanilla_volumes + minecraft_volumes }}"
  when: not minecraft_paper

- name: Ensure Docker volumes to mount are paper flavor
  ansible.builtin.set_fact:
    docker_volumes: "{{ vanilla_volumes + paper_volumes + minecraft_volumes }}"
  when: minecraft_paper

- name: Determine how much memory to give Minecraft
  ansible.builtin.set_fact:
    minecraft_memory: "{{ (ansible_memory_mb.real.total * 0.8) | round | int }}"

- name: Determine ports to give Minecraft for vanilla flavor
  ansible.builtin.set_fact:
    minecraft_port:
      - "25565:25565"
  when: not minecraft_paper

- name: Determine ports to give Minecraft for paper flavors
  ansible.builtin.set_fact:
    minecraft_port:
      - "8123:8123"
      - "25565:25565"
      - "19132:19132/udp"
  when: minecraft_paper

- name: Ensure Minecraft container is created
  community.docker.docker_container:
    container_default_behavior: compatibility
    detach: true
    env:
      PUID: "{{ minecraft_uid | quote }}"
      PGID: "{{ minecraft_gid | quote }}"
    image: "{{ docker_image }}"
    interactive: false
    memory: "{{ minecraft_memory }}m"
    memory_reservation: "{{ minecraft_memory }}m"
    memory_swap: 0
    memory_swappiness: 0
    name: "{{ minecraft_name }}"
    ports: "{{ minecraft_port }}"
    restart_policy: always
    security_opts:
      - no-new-privileges:true
    state: present
    volumes: "{{ docker_volumes }}"
  notify: Restart minecraft

- name: Force all notified handlers to run at this point
  ansible.builtin.meta: flush_handlers
